name: Docker Image CI

on:
  push:
    branches: [ "ansible-terraform" ]
  pull_request:
    branches: [ "ansible-terraform" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
        docker build . --file nodeapp/getting-started-master/getting-started-master/app/Dockerfile --tag my-image-name:$(date +%d)
        docker login --username=${{ secrets.USERNAME }} --password=${{ secrets.PASSWORD }}
        docker tag my-image-name:$(date +%d) nikita1239/repo12:$(date +%d)
        docker push nikita1239/repo12:$(date +%d)
        sudo apt install curl

    - name: Run docker image
      run: |
        docker run -dp 3000:3000 nikita1239/repo12:$(date +%d) 
        docker ps
        netstat -tulpn
    
      
    
